/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Cached
 */
export interface Cached {
    /**
     * URL of collection avatar
     * @type {string}
     * @memberof Cached
     */
    avatar?: string;
    /**
     * URL of collection banner
     * @type {string}
     * @memberof Cached
     */
    banner?: string;
    /**
     * URL of collection tile
     * @type {string}
     * @memberof Cached
     */
    tileUri?: string;
    /**
     * URL of collection thumbnail
     * @type {string}
     * @memberof Cached
     */
    thumbnail?: string;
}

/**
 * Check if a given object implements the Cached interface.
 */
export function instanceOfCached(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CachedFromJSON(json: any): Cached {
    return CachedFromJSONTyped(json, false);
}

export function CachedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cached {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'avatar': !exists(json, 'avatar') ? undefined : json['avatar'],
        'banner': !exists(json, 'banner') ? undefined : json['banner'],
        'tileUri': !exists(json, 'tileUri') ? undefined : json['tileUri'],
        'thumbnail': !exists(json, 'thumbnail') ? undefined : json['thumbnail'],
    };
}

export function CachedToJSON(value?: Cached | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'avatar': value.avatar,
        'banner': value.banner,
        'tileUri': value.tileUri,
        'thumbnail': value.thumbnail,
    };
}

