/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CounterfactualWalletInfo
 */
export interface CounterfactualWalletInfo {
    /**
     * accountId
     * @type {number}
     * @memberof CounterfactualWalletInfo
     */
    accountId: number;
    /**
     * wallet
     * @type {string}
     * @memberof CounterfactualWalletInfo
     */
    wallet: string;
    /**
     * walletFactory
     * @type {string}
     * @memberof CounterfactualWalletInfo
     */
    walletFactory: string;
    /**
     * walletSalt
     * @type {string}
     * @memberof CounterfactualWalletInfo
     */
    walletSalt: string;
    /**
     * walletOwner
     * @type {string}
     * @memberof CounterfactualWalletInfo
     */
    walletOwner: string;
}

/**
 * Check if a given object implements the CounterfactualWalletInfo interface.
 */
export function instanceOfCounterfactualWalletInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "wallet" in value;
    isInstance = isInstance && "walletFactory" in value;
    isInstance = isInstance && "walletSalt" in value;
    isInstance = isInstance && "walletOwner" in value;

    return isInstance;
}

export function CounterfactualWalletInfoFromJSON(json: any): CounterfactualWalletInfo {
    return CounterfactualWalletInfoFromJSONTyped(json, false);
}

export function CounterfactualWalletInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CounterfactualWalletInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'wallet': json['wallet'],
        'walletFactory': json['walletFactory'],
        'walletSalt': json['walletSalt'],
        'walletOwner': json['walletOwner'],
    };
}

export function CounterfactualWalletInfoToJSON(value?: CounterfactualWalletInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountId': value.accountId,
        'wallet': value.wallet,
        'walletFactory': value.walletFactory,
        'walletSalt': value.walletSalt,
        'walletOwner': value.walletOwner,
    };
}

