/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExtraProperties } from './ExtraProperties';
import {
    ExtraPropertiesFromJSON,
    ExtraPropertiesFromJSONTyped,
    ExtraPropertiesToJSON,
} from './ExtraProperties';

/**
 * 
 * @export
 * @interface Extra
 */
export interface Extra {
    /**
     * 
     * @type {ExtraProperties}
     * @memberof Extra
     */
    properties?: ExtraProperties;
    /**
     * Where this collection initially created
     * @type {string}
     * @memberof Extra
     */
    mintChannel?: string;
}

/**
 * Check if a given object implements the Extra interface.
 */
export function instanceOfExtra(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExtraFromJSON(json: any): Extra {
    return ExtraFromJSONTyped(json, false);
}

export function ExtraFromJSONTyped(json: any, ignoreDiscriminator: boolean): Extra {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'properties': !exists(json, 'properties') ? undefined : ExtraPropertiesFromJSON(json['properties']),
        'mintChannel': !exists(json, 'mintChannel') ? undefined : json['mintChannel'],
    };
}

export function ExtraToJSON(value?: Extra | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'properties': ExtraPropertiesToJSON(value.properties),
        'mintChannel': value.mintChannel,
    };
}

