/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LockAssetResponse
 */
export interface LockAssetResponse {
    /**
     * The hash identifier set by the user at the time of submission, can use this hash to get info
     * @type {string}
     * @memberof LockAssetResponse
     */
    hash?: string;
    /**
     * isIdempotent
     * @type {boolean}
     * @memberof LockAssetResponse
     */
    isIdempotent?: boolean;
}

/**
 * Check if a given object implements the LockAssetResponse interface.
 */
export function instanceOfLockAssetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LockAssetResponseFromJSON(json: any): LockAssetResponse {
    return LockAssetResponseFromJSONTyped(json, false);
}

export function LockAssetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockAssetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
        'isIdempotent': !exists(json, 'isIdempotent') ? undefined : json['isIdempotent'],
    };
}

export function LockAssetResponseToJSON(value?: LockAssetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hash': value.hash,
        'isIdempotent': value.isIdempotent,
    };
}

