/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LockAssetRequestToken
 */
export interface LockAssetRequestToken {
    /**
     * 
     * @type {number}
     * @memberof LockAssetRequestToken
     */
    tokenId: number;
    /**
     * 
     * @type {string}
     * @memberof LockAssetRequestToken
     */
    volume: string;
}

/**
 * Check if a given object implements the LockAssetRequestToken interface.
 */
export function instanceOfLockAssetRequestToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tokenId" in value;
    isInstance = isInstance && "volume" in value;

    return isInstance;
}

export function LockAssetRequestTokenFromJSON(json: any): LockAssetRequestToken {
    return LockAssetRequestTokenFromJSONTyped(json, false);
}

export function LockAssetRequestTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockAssetRequestToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenId': json['tokenId'],
        'volume': json['volume'],
    };
}

export function LockAssetRequestTokenToJSON(value?: LockAssetRequestToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tokenId': value.tokenId,
        'volume': value.volume,
    };
}

