/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NftOrderErc20Token } from './NftOrderErc20Token';
import {
    NftOrderErc20TokenFromJSON,
    NftOrderErc20TokenFromJSONTyped,
    NftOrderErc20TokenToJSON,
} from './NftOrderErc20Token';
import type { NftOrderNftToken } from './NftOrderNftToken';
import {
    NftOrderNftTokenFromJSON,
    NftOrderNftTokenFromJSONTyped,
    NftOrderNftTokenToJSON,
} from './NftOrderNftToken';

/**
 * 
 * @export
 * @interface NftTakerOrder
 */
export interface NftTakerOrder {
    /**
     * exchangeAddress in exchange info
     * @type {string}
     * @memberof NftTakerOrder
     */
    exchange: string;
    /**
     * accountId
     * @type {number}
     * @memberof NftTakerOrder
     */
    accountId: number;
    /**
     * storageId
     * @type {number}
     * @memberof NftTakerOrder
     */
    storageId: number;
    /**
     * 
     * @type {NftOrderErc20Token}
     * @memberof NftTakerOrder
     */
    sellToken: NftOrderErc20Token;
    /**
     * 
     * @type {NftOrderNftToken}
     * @memberof NftTakerOrder
     */
    buyToken: NftOrderNftToken;
    /**
     * allOrNone
     * @type {boolean}
     * @memberof NftTakerOrder
     */
    allOrNone: boolean;
    /**
     * fillAmountBOrS
     * @type {boolean}
     * @memberof NftTakerOrder
     */
    fillAmountBOrS: boolean;
    /**
     * timestamp for transfer to become invalid, seconds
     * @type {number}
     * @memberof NftTakerOrder
     */
    validUntil: number;
    /**
     * maximum order fee that the user can accept, value range (in ten thousandths) 1 ~ 5000
     * @type {number}
     * @memberof NftTakerOrder
     */
    maxFeeBips: number;
    /**
     * eddsa signature of the eddsa hash
     * @type {string}
     * @memberof NftTakerOrder
     */
    eddsaSignature: string;
    /**
     * taker address
     * @type {string}
     * @memberof NftTakerOrder
     */
    taker?: string;
}

/**
 * Check if a given object implements the NftTakerOrder interface.
 */
export function instanceOfNftTakerOrder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "exchange" in value;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "storageId" in value;
    isInstance = isInstance && "sellToken" in value;
    isInstance = isInstance && "buyToken" in value;
    isInstance = isInstance && "allOrNone" in value;
    isInstance = isInstance && "fillAmountBOrS" in value;
    isInstance = isInstance && "validUntil" in value;
    isInstance = isInstance && "maxFeeBips" in value;
    isInstance = isInstance && "eddsaSignature" in value;

    return isInstance;
}

export function NftTakerOrderFromJSON(json: any): NftTakerOrder {
    return NftTakerOrderFromJSONTyped(json, false);
}

export function NftTakerOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftTakerOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exchange': json['exchange'],
        'accountId': json['accountId'],
        'storageId': json['storageId'],
        'sellToken': NftOrderErc20TokenFromJSON(json['sellToken']),
        'buyToken': NftOrderNftTokenFromJSON(json['buyToken']),
        'allOrNone': json['allOrNone'],
        'fillAmountBOrS': json['fillAmountBOrS'],
        'validUntil': json['validUntil'],
        'maxFeeBips': json['maxFeeBips'],
        'eddsaSignature': json['eddsaSignature'],
        'taker': !exists(json, 'taker') ? undefined : json['taker'],
    };
}

export function NftTakerOrderToJSON(value?: NftTakerOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exchange': value.exchange,
        'accountId': value.accountId,
        'storageId': value.storageId,
        'sellToken': NftOrderErc20TokenToJSON(value.sellToken),
        'buyToken': NftOrderNftTokenToJSON(value.buyToken),
        'allOrNone': value.allOrNone,
        'fillAmountBOrS': value.fillAmountBOrS,
        'validUntil': value.validUntil,
        'maxFeeBips': value.maxFeeBips,
        'eddsaSignature': value.eddsaSignature,
        'taker': value.taker,
    };
}

