/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NftTradeFill
 */
export interface NftTradeFill {
    /**
     * the order hash
     * @type {string}
     * @memberof NftTradeFill
     */
    orderHash?: string;
    /**
     * the orders sell fill
     * @type {object}
     * @memberof NftTradeFill
     */
    sellFilled?: object;
    /**
     * the orders buy fill
     * @type {object}
     * @memberof NftTradeFill
     */
    buyFilled?: object;
    /**
     * the orders fee
     * @type {object}
     * @memberof NftTradeFill
     */
    fee?: object;
}

/**
 * Check if a given object implements the NftTradeFill interface.
 */
export function instanceOfNftTradeFill(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NftTradeFillFromJSON(json: any): NftTradeFill {
    return NftTradeFillFromJSONTyped(json, false);
}

export function NftTradeFillFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftTradeFill {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderHash': !exists(json, 'orderHash') ? undefined : json['orderHash'],
        'sellFilled': !exists(json, 'sellFilled') ? undefined : json['sellFilled'],
        'buyFilled': !exists(json, 'buyFilled') ? undefined : json['buyFilled'],
        'fee': !exists(json, 'fee') ? undefined : json['fee'],
    };
}

export function NftTradeFillToJSON(value?: NftTradeFill | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderHash': value.orderHash,
        'sellFilled': value.sellFilled,
        'buyFilled': value.buyFilled,
        'fee': value.fee,
    };
}

