/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PendingBalance
 */
export interface PendingBalance {
    /**
     * Withdrawal pending balance which means the token is in withdrawal state but not arrived L1
     * @type {string}
     * @memberof PendingBalance
     */
    withdraw: string;
    /**
     * Deposit pending balance which means the token is in deposit state but not arrived L2
     * @type {string}
     * @memberof PendingBalance
     */
    deposit: string;
}

/**
 * Check if a given object implements the PendingBalance interface.
 */
export function instanceOfPendingBalance(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "withdraw" in value;
    isInstance = isInstance && "deposit" in value;

    return isInstance;
}

export function PendingBalanceFromJSON(json: any): PendingBalance {
    return PendingBalanceFromJSONTyped(json, false);
}

export function PendingBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingBalance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'withdraw': json['withdraw'],
        'deposit': json['deposit'],
    };
}

export function PendingBalanceToJSON(value?: PendingBalance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'withdraw': value.withdraw,
        'deposit': value.deposit,
    };
}

