/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Preference
 */
export interface Preference {
    /**
     * 
     * @type {boolean}
     * @memberof Preference
     */
    favourite?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Preference
     */
    hide?: boolean;
}

/**
 * Check if a given object implements the Preference interface.
 */
export function instanceOfPreference(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PreferenceFromJSON(json: any): Preference {
    return PreferenceFromJSONTyped(json, false);
}

export function PreferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Preference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'favourite': !exists(json, 'favourite') ? undefined : json['favourite'],
        'hide': !exists(json, 'hide') ? undefined : json['hide'],
    };
}

export function PreferenceToJSON(value?: Preference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'favourite': value.favourite,
        'hide': value.hide,
    };
}

