/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResolveNameInfo
 */
export interface ResolveNameInfo {
    /**
     * Resolved name or empty string
     * @type {string}
     * @memberof ResolveNameInfo
     */
    data: string;
}

/**
 * Check if a given object implements the ResolveNameInfo interface.
 */
export function instanceOfResolveNameInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ResolveNameInfoFromJSON(json: any): ResolveNameInfo {
    return ResolveNameInfoFromJSONTyped(json, false);
}

export function ResolveNameInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolveNameInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function ResolveNameInfoToJSON(value?: ResolveNameInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
    };
}

