/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultInfoResultInfo
 */
export interface ResultInfoResultInfo {
    /**
     * 
     * @type {number}
     * @memberof ResultInfoResultInfo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultInfoResultInfo
     */
    msg?: string;
    /**
     * 
     * @type {string}
     * @memberof ResultInfoResultInfo
     */
    message?: string;
}

/**
 * Check if a given object implements the ResultInfoResultInfo interface.
 */
export function instanceOfResultInfoResultInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResultInfoResultInfoFromJSON(json: any): ResultInfoResultInfo {
    return ResultInfoResultInfoFromJSONTyped(json, false);
}

export function ResultInfoResultInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultInfoResultInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ResultInfoResultInfoToJSON(value?: ResultInfoResultInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'msg': value.msg,
        'message': value.message,
    };
}

