/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Times
 */
export interface Times {
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof Times
     */
    createdAt?: number;
    /**
     * Unix timestamp in milliseconds
     * @type {number}
     * @memberof Times
     */
    updatedAt?: number;
}

/**
 * Check if a given object implements the Times interface.
 */
export function instanceOfTimes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TimesFromJSON(json: any): Times {
    return TimesFromJSONTyped(json, false);
}

export function TimesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Times {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
    };
}

export function TimesToJSON(value?: Times | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
    };
}

