/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenFeeInfo
 */
export interface TokenFeeInfo {
    /**
     * fee token
     * @type {string}
     * @memberof TokenFeeInfo
     */
    token: string;
    /**
     * fee amount
     * @type {string}
     * @memberof TokenFeeInfo
     */
    fee: string;
    /**
     * token discount. 0.8 means 80% of the fee
     * @type {number}
     * @memberof TokenFeeInfo
     */
    discount?: number;
}

/**
 * Check if a given object implements the TokenFeeInfo interface.
 */
export function instanceOfTokenFeeInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "fee" in value;

    return isInstance;
}

export function TokenFeeInfoFromJSON(json: any): TokenFeeInfo {
    return TokenFeeInfoFromJSONTyped(json, false);
}

export function TokenFeeInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenFeeInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'fee': json['fee'],
        'discount': !exists(json, 'discount') ? undefined : json['discount'],
    };
}

export function TokenFeeInfoToJSON(value?: TokenFeeInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'fee': value.fee,
        'discount': value.discount,
    };
}

