/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnlockAssetRequest
 */
export interface UnlockAssetRequest {
    /**
     * accountId
     * @type {number}
     * @memberof UnlockAssetRequest
     */
    accountId: number;
    /**
     * the lock hash returned from lockAsset
     * @type {string}
     * @memberof UnlockAssetRequest
     */
    hash: string;
}

/**
 * Check if a given object implements the UnlockAssetRequest interface.
 */
export function instanceOfUnlockAssetRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "hash" in value;

    return isInstance;
}

export function UnlockAssetRequestFromJSON(json: any): UnlockAssetRequest {
    return UnlockAssetRequestFromJSONTyped(json, false);
}

export function UnlockAssetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnlockAssetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'hash': json['hash'],
    };
}

export function UnlockAssetRequestToJSON(value?: UnlockAssetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountId': value.accountId,
        'hash': value.hash,
    };
}

