/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserApiKey
 */
export interface UserApiKey {
    /**
     * ApiKey
     * @type {string}
     * @memberof UserApiKey
     */
    apiKey: string;
}

/**
 * Check if a given object implements the UserApiKey interface.
 */
export function instanceOfUserApiKey(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "apiKey" in value;

    return isInstance;
}

export function UserApiKeyFromJSON(json: any): UserApiKey {
    return UserApiKeyFromJSONTyped(json, false);
}

export function UserApiKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserApiKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiKey': json['apiKey'],
    };
}

export function UserApiKeyToJSON(value?: UserApiKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiKey': value.apiKey,
    };
}

