/* tslint:disable */
/* eslint-disable */
/**
 * SDK for Loopring Layer 2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CombinedBalance } from './CombinedBalance';
import {
    CombinedBalanceFromJSON,
    CombinedBalanceFromJSONTyped,
    CombinedBalanceToJSON,
} from './CombinedBalance';

/**
 * 
 * @export
 * @interface UserNftBalancesInfo
 */
export interface UserNftBalancesInfo {
    /**
     * Total number
     * @type {number}
     * @memberof UserNftBalancesInfo
     */
    totalNum: number;
    /**
     * 
     * @type {Array<CombinedBalance>}
     * @memberof UserNftBalancesInfo
     */
    data: Array<CombinedBalance>;
}

/**
 * Check if a given object implements the UserNftBalancesInfo interface.
 */
export function instanceOfUserNftBalancesInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalNum" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function UserNftBalancesInfoFromJSON(json: any): UserNftBalancesInfo {
    return UserNftBalancesInfoFromJSONTyped(json, false);
}

export function UserNftBalancesInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserNftBalancesInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalNum': json['totalNum'],
        'data': ((json['data'] as Array<any>).map(CombinedBalanceFromJSON)),
    };
}

export function UserNftBalancesInfoToJSON(value?: UserNftBalancesInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalNum': value.totalNum,
        'data': ((value.data as Array<any>).map(CombinedBalanceToJSON)),
    };
}

